### ISSUE TITLE
run pingmq error:flag redefined: log_dir

### ISSUE THREAD

**Issue by qianrongguo** [zentures/surgemq#63]
when i run example/pingmq, 
error like this:
```text
./pingmq flag redefined: log_dir
panic: ./pingmq flag redefined: log_dir

goroutine 1 [running]:
flag.(*FlagSet).Var(0xc0000a4120, 0x72f8c0, 0xc000091750, 0x6e7dfd, 0x7, 0x6f3a95, 0x2f)
	/usr/local/go/src/flag/flag.go:805 +0x529
flag.(*FlagSet).StringVar(0xc0000a4120, 0xc000091750, 0x6e7dfd, 0x7, 0x0, 0x0, 0x6f3a95, 0x2f)
	/usr/local/go/src/flag/flag.go:708 +0x8a
flag.(*FlagSet).String(0xc0000a4120, 0x6e7dfd, 0x7, 0x0, 0x0, 0x6f3a95, 0x2f, 0xc000091740)
	/usr/local/go/src/flag/flag.go:721 +0x8b
flag.String(0x6e7dfd, 0x7, 0x0, 0x0, 0x6f3a95, 0x2f, 0xc000091720)
	/usr/local/go/src/flag/flag.go:728 +0x69

```

**Comment by qianrongguo** [comment]
go version go1.11.2 linux/amd64

**Comment by DrAuYueng** [comment]
> when i run example/pingmq,
> error like this:
> 
> ```
> ./pingmq flag redefined: log_dir
> panic: ./pingmq flag redefined: log_dir
> 
> goroutine 1 [running]:
> flag.(*FlagSet).Var(0xc0000a4120, 0x72f8c0, 0xc000091750, 0x6e7dfd, 0x7, 0x6f3a95, 0x2f)
> 	/usr/local/go/src/flag/flag.go:805 +0x529
> flag.(*FlagSet).StringVar(0xc0000a4120, 0xc000091750, 0x6e7dfd, 0x7, 0x0, 0x0, 0x6f3a95, 0x2f)
> 	/usr/local/go/src/flag/flag.go:708 +0x8a
> flag.(*FlagSet).String(0xc0000a4120, 0x6e7dfd, 0x7, 0x0, 0x0, 0x6f3a95, 0x2f, 0xc000091740)
> 	/usr/local/go/src/flag/flag.go:721 +0x8b
> flag.String(0x6e7dfd, 0x7, 0x0, 0x0, 0x6f3a95, 0x2f, 0xc000091720)
> 	/usr/local/go/src/flag/flag.go:728 +0x69
> ```

modify github.com/surge/netx/ping.go
in the import block,change "github.com/surgebase/glog" to "github.com/surge/glog"
work for me!
